<!DOCTYPE html>
<html lang="en-in"><head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script async src="https://cdn.ampproject.org/v0.js"></script>
<script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
<title>Sagar Bazar Day Panel Chart | Fastest Online Result</title>
<meta name="description" content="Get yourself equipped with our latest Sagar Bazar Day Panel Chart record, it shows all the live results, and real-time updates, and has all the previous data.">
<meta name="keywords" content="Sagar Bazar day panel chart, Sagar Bazar day panel chart, Sagar Bazar day patti chart, Sagar Bazar day panel record, Sagar Bazar day panel record, Sagar Bazar day pana chart">
<link rel="canonical" href="https://dpboss.boston/panel-chart-record/sagar-day.php"/>
<meta name="robots" content="follow, all">
<?php include_once('panel_style_amp.php'); ?>
</head>
<body>
<?php include_once('../name_amp.php'); ?>
<div class="container-fluid">
<div>
			<div class="panel panel-info">
            	<div class="panel-heading text-center" style="background: #3f51b5 !important;"><h1  style="font-size: 22px;color:#fff; text-shadow: 0px 0px;">Sagar Bazar Day Panel Chart </h1></div>
                <div class="panel-body">
                	<table style="width: 100%; text-align:center;" class="panel-chart chart-table" cellpadding="2">
                	<thead> 
                	<tr>
                		<th>Date</th>
                		<th colspan="3">Mon</th>
                		<th colspan="3">Tue</th>
                		<th colspan="3">Wed</th>
                		<th colspan="3">Thu</th>
                		<th colspan="3">Fri</th>
										<th colspan="3">Sat</th>
                		<th colspan="3">Sun</th>
                	</tr>
                	</thead>                	
                	<tbody>
<tr>
<td>04/07/2022<br />to<br />10/07/2022</td>
<td class="r">1<br>5<br>0</td>
<td class="r">66</td>
<td class="r">3<br>6<br>7</td>
<td class="">4<br>5<br>0</td>
<td class="">91</td>
<td class="">2<br>3<br>6</td>
<td class="">7<br>8<br>0</td>
<td class="">54</td>
<td class="">6<br>8<br>0</td>
<td class="">4<br>7<br>9</td>
<td class="">04</td>
<td class="">4<br>0<br>0</td>
<td class="">4<br>8<br>0</td>
<td class="">26</td>
<td class="">2<br>6<br>8</td>
<td class="r">1<br>2<br>4</td>
<td class="r">77</td>
<td class="r">7<br>0<br>0</td>
<td class="">2<br>6<br>8</td>
<td class="">60</td>
<td class="">1<br>9<br>0</td>
</tr> <tr>
<td>11/07/2022<br />to<br />17/07/2022</td>
<td class="">1<br>8<br>0</td>
<td class="">91</td>
<td class="">3<br>8<br>0</td>
<td class="">3<br>7<br>9</td>
<td class="">96</td>
<td class="">1<br>5<br>0</td>
<td class="">1<br>2<br>8</td>
<td class="">18</td>
<td class="">4<br>4<br>0</td>
<td class="r">1<br>7<br>0</td>
<td class="r">83</td>
<td class="r">1<br>4<br>8</td>
<td class="">4<br>8<br>9</td>
<td class="">10</td>
<td class="">5<br>6<br>9</td>
<td class="">3<br>6<br>7</td>
<td class="">67</td>
<td class="">3<br>7<br>7</td>
<td class="">2<br>3<br>5</td>
<td class="">06</td>
<td class="">3<br>3<br>0</td>
</tr> <tr>
<td>18/07/2022<br />to<br />24/07/2022</td>
<td class="r">7<br>7<br>9</td>
<td class="r">33</td>
<td class="r">6<br>7<br>0</td>
<td class="r">5<br>9<br>0</td>
<td class="r">49</td>
<td class="r">2<br>2<br>5</td>
<td class="">1<br>7<br>8</td>
<td class="">60</td>
<td class="">2<br>3<br>5</td>
<td class="">1<br>5<br>0</td>
<td class="">67</td>
<td class="">3<br>5<br>9</td>
<td class="">2<br>4<br>8</td>
<td class="">40</td>
<td class="">5<br>5<br>0</td>
<td class="">2<br>7<br>0</td>
<td class="">92</td>
<td class="">3<br>4<br>5</td>
<td class="r">1<br>5<br>6</td>
<td class="r">22</td>
<td class="r">2<br>0<br>0</td>
</tr> <tr>
<td>25/07/2022<br />to<br />31/07/2022</td>
<td class="r">2<br>2<br>5</td>
<td class="r">94</td>
<td class="r">4<br>0<br>0</td>
<td class="">5<br>6<br>0</td>
<td class="">14</td>
<td class="">2<br>5<br>7</td>
<td class="">4<br>4<br>7</td>
<td class="">59</td>
<td class="">2<br>3<br>4</td>
<td class="r">5<br>7<br>8</td>
<td class="r">05</td>
<td class="r">2<br>3<br>0</td>
<td class="">1<br>7<br>8</td>
<td class="">64</td>
<td class="">1<br>5<br>8</td>
<td class="">8<br>9<br>0</td>
<td class="">70</td>
<td class="">1<br>9<br>0</td>
<td class="">7<br>8<br>9</td>
<td class="">47</td>
<td class="">2<br>6<br>9</td>
</tr> <tr>
<td>01/08/2022<br />to<br />07/08/2022</td>
<td class="r">2<br>5<br>0</td>
<td class="r">72</td>
<td class="r">3<br>9<br>0</td>
<td class="r">3<br>5<br>8</td>
<td class="r">66</td>
<td class="r">1<br>5<br>0</td>
<td class="">2<br>7<br>8</td>
<td class="">78</td>
<td class="">4<br>4<br>0</td>
<td class="">5<br>6<br>0</td>
<td class="">19</td>
<td class="">1<br>8<br>0</td>
<td class="r">4<br>6<br>9</td>
<td class="r">94</td>
<td class="r">3<br>4<br>7</td>
<td class="">1<br>3<br>3</td>
<td class="">70</td>
<td class="">5<br>5<br>0</td>
<td class="">6<br>7<br>9</td>
<td class="">25</td>
<td class="">2<br>3<br>0</td>
</tr> <tr>
<td>08/08/2022<br />to<br />14/08/2022</td>
<td class="">1<br>6<br>0</td>
<td class="">79</td>
<td class="">2<br>2<br>5</td>
<td class="">3<br>6<br>7</td>
<td class="">64</td>
<td class="">7<br>8<br>9</td>
<td class="">4<br>7<br>8</td>
<td class="">91</td>
<td class="">1<br>2<br>8</td>
<td class="">1<br>2<br>6</td>
<td class="">95</td>
<td class="">3<br>4<br>8</td>
<td class="">2<br>7<br>0</td>
<td class="">91</td>
<td class="">1<br>3<br>7</td>
<td class="">7<br>7<br>9</td>
<td class="">37</td>
<td class="">1<br>2<br>4</td>
<td class="r">1<br>8<br>9</td>
<td class="r">83</td>
<td class="r">3<br>0<br>0</td>
</tr> <tr>
<td>15/08/2022<br />to<br />21/08/2022</td>
<td class="r">*<br>*<br>*</td>
<td class="r">**</td>
<td class="r">*<br>*<br>*</td>
<td class="r">4<br>8<br>0</td>
<td class="r">22</td>
<td class="r">2<br>5<br>5</td>
<td class="">1<br>9<br>0</td>
<td class="">08</td>
<td class="">3<br>7<br>8</td>
<td class="">5<br>7<br>0</td>
<td class="">23</td>
<td class="">1<br>3<br>9</td>
<td class="">5<br>0<br>0</td>
<td class="">59</td>
<td class="">2<br>8<br>9</td>
<td class="">5<br>7<br>8</td>
<td class="">04</td>
<td class="">6<br>8<br>0</td>
<td class="">6<br>8<br>9</td>
<td class="">37</td>
<td class="">1<br>6<br>0</td>
</tr> <tr>
<td>22/08/2022<br />to<br />28/08/2022</td>
<td class="">5<br>5<br>7</td>
<td class="">75</td>
<td class="">6<br>9<br>0</td>
<td class="r">2<br>5<br>8</td>
<td class="r">55</td>
<td class="r">1<br>4<br>0</td>
<td class="">1<br>4<br>4</td>
<td class="">97</td>
<td class="">1<br>8<br>8</td>
<td class="">6<br>6<br>9</td>
<td class="">13</td>
<td class="">4<br>9<br>0</td>
<td class="">5<br>8<br>9</td>
<td class="">26</td>
<td class="">3<br>5<br>8</td>
<td class="">2<br>6<br>9</td>
<td class="">79</td>
<td class="">1<br>8<br>0</td>
<td class="">1<br>3<br>3</td>
<td class="">70</td>
<td class="">1<br>4<br>5</td>
</tr> <tr>
<td>29/08/2022<br />to<br />04/09/2022</td>
<td class="">3<br>6<br>6</td>
<td class="">51</td>
<td class="">2<br>9<br>0</td>
<td class="">2<br>6<br>0</td>
<td class="">84</td>
<td class="">2<br>6<br>6</td>
<td class="">2<br>6<br>7</td>
<td class="">58</td>
<td class="">1<br>7<br>0</td>
<td class="">1<br>3<br>4</td>
<td class="">84</td>
<td class="">3<br>4<br>7</td>
<td class="">5<br>7<br>9</td>
<td class="">14</td>
<td class="">1<br>6<br>7</td>
<td class="">2<br>3<br>4</td>
<td class="">93</td>
<td class="">2<br>3<br>8</td>
<td class="">1<br>4<br>0</td>
<td class="">56</td>
<td class="">1<br>7<br>8</td>
</tr> <tr>
<td>05/09/2022<br />to<br />11/09/2022</td>
<td class="">3<br>4<br>5</td>
<td class="">20</td>
<td class="">3<br>7<br>0</td>
<td class="">2<br>5<br>6</td>
<td class="">35</td>
<td class="">6<br>9<br>0</td>
<td class="">2<br>6<br>8</td>
<td class="">68</td>
<td class="">5<br>6<br>7</td>
<td class="">6<br>7<br>9</td>
<td class="">26</td>
<td class="">4<br>4<br>8</td>
<td class="">2<br>4<br>0</td>
<td class="">60</td>
<td class="">4<br>6<br>0</td>
<td class="r">4<br>9<br>0</td>
<td class="r">38</td>
<td class="r">3<br>5<br>0</td>
<td class="">1<br>4<br>8</td>
<td class="">32</td>
<td class="">4<br>8<br>0</td>
</tr> <tr>
<td>12/09/2022<br />to<br />18/09/2022</td>
<td class="">1<br>6<br>0</td>
<td class="">76</td>
<td class="">3<br>4<br>9</td>
<td class="">1<br>2<br>7</td>
<td class="">04</td>
<td class="">7<br>7<br>0</td>
<td class="r">4<br>6<br>7</td>
<td class="r">72</td>
<td class="r">5<br>7<br>0</td>
<td class="">3<br>8<br>9</td>
<td class="">03</td>
<td class="">1<br>4<br>8</td>
<td class="">7<br>8<br>9</td>
<td class="">40</td>
<td class="">2<br>3<br>5</td>
<td class="r">6<br>6<br>7</td>
<td class="r">94</td>
<td class="r">1<br>6<br>7</td>
<td class="">3<br>4<br>9</td>
<td class="">62</td>
<td class="">5<br>8<br>9</td>
</tr> <tr>
<td>19/09/2022<br />to<br />25/09/2022</td>
<td class="">7<br>9<br>0</td>
<td class="">64</td>
<td class="">3<br>5<br>6</td>
<td class="">1<br>2<br>6</td>
<td class="">97</td>
<td class="">3<br>7<br>7</td>
<td class="r">1<br>8<br>0</td>
<td class="r">94</td>
<td class="r">3<br>5<br>6</td>
<td class="">3<br>4<br>9</td>
<td class="">60</td>
<td class="">2<br>8<br>0</td>
<td class="">6<br>8<br>9</td>
<td class="">32</td>
<td class="">1<br>5<br>6</td>
<td class="">5<br>5<br>0</td>
<td class="">02</td>
<td class="">6<br>6<br>0</td>
<td class="">7<br>7<br>0</td>
<td class="">45</td>
<td class="">6<br>9<br>0</td>
</tr> <tr>
<td>26/09/2022<br />to<br />02/10/2022</td>
<td class="">6<br>8<br>9</td>
<td class="">36</td>
<td class="">4<br>5<br>7</td>
<td class="">1<br>3<br>5</td>
<td class="">90</td>
<td class="">1<br>9<br>0</td>
<td class="r">7<br>8<br>9</td>
<td class="r">49</td>
<td class="r">3<br>6<br>0</td>
<td class="">2<br>6<br>0</td>
<td class="">85</td>
<td class="">2<br>5<br>8</td>
<td class="">5<br>7<br>8</td>
<td class="">03</td>
<td class="">4<br>9<br>0</td>
<td class="">1<br>1<br>0</td>
<td class="">28</td>
<td class="">1<br>2<br>5</td>
<td class="">1<br>8<br>9</td>
<td class="">80</td>
<td class="">4<br>6<br>0</td>
</tr> <tr>
<td>03/10/2022<br />to<br />09/10/2022</td>
<td class="">8<br>8<br>9</td>
<td class="">58</td>
<td class="">3<br>7<br>8</td>
<td class="r">7<br>8<br>0</td>
<td class="r">50</td>
<td class="r">1<br>9<br>0</td>
<td class="">1<br>8<br>8</td>
<td class="">70</td>
<td class="">2<br>8<br>0</td>
<td class="r">2<br>3<br>0</td>
<td class="r">55</td>
<td class="r">1<br>4<br>0</td>
<td class="">3<br>4<br>8</td>
<td class="">52</td>
<td class="">4<br>8<br>0</td>
<td class="">9<br>9<br>0</td>
<td class="">87</td>
<td class="">2<br>7<br>8</td>
<td class="">5<br>9<br>0</td>
<td class="">43</td>
<td class="">2<br>3<br>8</td>
</tr> <tr>
<td>10/10/2022<br />to<br />16/10/2022</td>
<td class="">5<br>6<br>0</td>
<td class="">15</td>
<td class="">4<br>5<br>6</td>
<td class="">7<br>8<br>0</td>
<td class="">52</td>
<td class="">5<br>8<br>9</td>
<td class="">3<br>3<br>9</td>
<td class="">52</td>
<td class="">1<br>2<br>9</td>
<td class="">2<br>6<br>8</td>
<td class="">65</td>
<td class="">2<br>4<br>9</td>
<td class="">2<br>4<br>4</td>
<td class="">09</td>
<td class="">2<br>3<br>4</td>
<td class="">3<br>7<br>9</td>
<td class="">92</td>
<td class="">1<br>5<br>6</td>
<td class="">2<br>7<br>8</td>
<td class="">71</td>
<td class="">3<br>8<br>0</td>
</tr> <tr>
<td>17/10/2022<br />to<br />23/10/2022</td>
<td class="">5<br>5<br>7</td>
<td class="">70</td>
<td class="">1<br>3<br>6</td>
<td class="r">4<br>5<br>9</td>
<td class="r">88</td>
<td class="r">3<br>6<br>9</td>
<td class="">7<br>8<br>8</td>
<td class="">36</td>
<td class="">2<br>4<br>0</td>
<td class="">4<br>5<br>6</td>
<td class="">59</td>
<td class="">4<br>7<br>8</td>
<td class="">3<br>4<br>7</td>
<td class="">41</td>
<td class="">1<br>4<br>6</td>
<td class="">3<br>7<br>8</td>
<td class="">89</td>
<td class="">3<br>6<br>0</td>
<td class="">1<br>9<br>0</td>
<td class="">01</td>
<td class="">2<br>4<br>5</td>
</tr> <tr>
<td>24/10/2022<br />to<br />30/10/2022</td>
<td class="r">*<br>*<br>*</td>
<td class="r">**</td>
<td class="r">*<br>*<br>*</td>
<td class="r">*<br>*<br>*</td>
<td class="r">**</td>
<td class="r">*<br>*<br>*</td>
<td class="">2<br>3<br>0</td>
<td class="">59</td>
<td class="">2<br>7<br>0</td>
<td class="">6<br>6<br>7</td>
<td class="">91</td>
<td class="">1<br>5<br>5</td>
<td class="">2<br>7<br>0</td>
<td class="">93</td>
<td class="">2<br>4<br>7</td>
<td class="">7<br>7<br>0</td>
<td class="">41</td>
<td class="">1<br>4<br>6</td>
<td class="">4<br>6<br>9</td>
<td class="">97</td>
<td class="">3<br>5<br>9</td>
</tr> <tr>
<td>31/10/2022<br />to<br />06/11/2022</td>
<td class="r">1<br>2<br>4</td>
<td class="r">77</td>
<td class="r">2<br>7<br>8</td>
<td class="">1<br>3<br>5</td>
<td class="">90</td>
<td class="">3<br>8<br>9</td>
<td class="">1<br>4<br>9</td>
<td class="">41</td>
<td class="">2<br>4<br>5</td>
<td class="">2<br>4<br>6</td>
<td class="">24</td>
<td class="">3<br>5<br>6</td>
<td class="r">2<br>5<br>9</td>
<td class="r">61</td>
<td class="r">1<br>2<br>8</td>
<td class="">6<br>7<br>8</td>
<td class="">12</td>
<td class="">3<br>4<br>5</td>
<td class="">4<br>9<br>0</td>
<td class="">30</td>
<td class="">5<br>6<br>9</td>
</tr> <tr>
<td>07/11/2022<br />to<br />13/11/2022</td>
<td class="r">7<br>8<br>9</td>
<td class="r">44</td>
<td class="r">3<br>4<br>7</td>
<td class="">2<br>6<br>9</td>
<td class="">79</td>
<td class="">4<br>5<br>0</td>
<td class="r">2<br>4<br>5</td>
<td class="r">16</td>
<td class="r">8<br>9<br>9</td>
<td class="r">1<br>3<br>9</td>
<td class="r">38</td>
<td class="r">5<br>6<br>7</td>
<td class="">2<br>5<br>8</td>
<td class="">52</td>
<td class="">1<br>3<br>8</td>
<td class="r">1<br>6<br>9</td>
<td class="r">61</td>
<td class="r">6<br>7<br>8</td>
<td class="r">2<br>3<br>4</td>
<td class="r">94</td>
<td class="r">6<br>8<br>0</td>
</tr> <tr>
<td>14/11/2022<br />to<br />20/11/2022</td>
<td class="">5<br>8<br>0</td>
<td class="">32</td>
<td class="">5<br>8<br>9</td>
<td class="">7<br>9<br>0</td>
<td class="">69</td>
<td class="">5<br>6<br>8</td>
<td class="">4<br>6<br>7</td>
<td class="">75</td>
<td class="">4<br>5<br>6</td>
<td class="">1<br>5<br>5</td>
<td class="">15</td>
<td class="">1<br>6<br>8</td>
<td class="">4<br>5<br>0</td>
<td class="">98</td>
<td class="">3<br>6<br>9</td>
<td class="">2<br>8<br>9</td>
<td class="">92</td>
<td class="">2<br>4<br>6</td>
<td class="">1<br>7<br>9</td>
<td class="">75</td>
<td class="">3<br>4<br>8</td>
</tr> <tr>
<td>21/11/2022<br />to<br />27/11/2022</td>

<td class="">1<br>5<br>8</td>
<td class="">46</td>
<td class="">1<br>7<br>8</td>
<td class="">1<br>3<br>5</td>
<td class="">92</td>
<td class="">2<br>3<br>7</td>
<td class="">3<br>4<br>8</td>
<td class="">58</td>
<td class="">4<br>6<br>8</td>
<td class="">4<br>5<br>8</td>
<td class="">78</td>
<td class="">5<br>6<br>7</td>
<td class="">1<br>5<br>7</td>
<td class="">31</td>
<td class="">4<br>7<br>0</td>
<td class="">5<br>9<br>0</td>
<td class="">45</td>
<td class="">1<br>5<br>9</td>
<td class="">3<br>6<br>8</td>
<td class="">70</td>
<td class="">4<br>7<br>9</td>
</tr> <tr>
<td>28/11/2022<br />to<br />04/12/2022</td>
<td class="">4<br>8<br>9</td>
<td class="">15</td>
<td class="">1<br>4<br>0</td>
<td class="">1<br>3<br>8</td>
<td class="">28</td>
<td class="">1<br>2<br>5</td>
<td class="">7<br>7<br>9</td>
<td class="">31</td>
<td class="">2<br>9<br>0</td>
<td class="">5<br>7<br>8</td>
<td class="">07</td>
<td class="">3<br>5<br>9</td>
<td class="">2<br>6<br>7</td>
<td class="">59</td>
<td class="">2<br>8<br>9</td>
<td class="">1<br>5<br>7</td>
<td class="">34</td>
<td class="">1<br>6<br>7</td>
<td class="">3<br>4<br>9</td>
<td class="">65</td>
<td class="">1<br>6<br>8</td>
</tr> <tr>
<td>05/12/2022<br />to<br />11/12/2022</td>
<td class="">8<br>8<br>9</td>
<td class="">52</td>
<td class="">1<br>4<br>7</td>
<td class="">1<br>6<br>9</td>
<td class="">69</td>
<td class="">3<br>6<br>0</td>
<td class="">3<br>4<br>6</td>
<td class="">37</td>
<td class="">8<br>9<br>0</td>
<td class="">1<br>2<br>3</td>
<td class="">65</td>
<td class="">1<br>5<br>9</td>
<td class="">5<br>8<br>0</td>
<td class="">36</td>
<td class="">1<br>7<br>8</td>
<td class="">3<br>6<br>8</td>
<td class="">71</td>
<td class="">5<br>7<br>9</td>
<td class="">4<br>5<br>9</td>
<td class="">86</td>
<td class="">2<br>7<br>7</td>
</tr> <tr>
<td>12/12/2022<br />to<br />18/12/2022</td>
<td class="">1<br>4<br>5</td>
<td class="">03</td>
<td class="">4<br>9<br>0</td>
<td class="">4<br>5<br>6</td>
<td class="">51</td>
<td class="">4<br>8<br>9</td>
<td class="">3<br>5<br>0</td>
<td class="">84</td>
<td class="">1<br>4<br>9</td>
<td class="">7<br>8<br>0</td>
<td class="">53</td>
<td class="">7<br>7<br>9</td>
<td class="">1<br>6<br>0</td>
<td class="">71</td>
<td class="">1<br>3<br>7</td>
<td class="">5<br>8<br>9</td>
<td class="">20</td>
<td class="">1<br>2<br>7</td>
<td class="">1<br>9<br>0</td>
<td class="">07</td>
<td class="">2<br>6<br>9</td>
</tr> <tr>
<td>19/12/2022<br />to<br />25/12/2022</td>
<td class="">6<br>7<br>8</td>
<td class="">18</td>
<td class="">3<br>6<br>9</td>
<td class="">3<br>5<br>6</td>
<td class="">47</td>
<td class="">8<br>9<br>0</td>
<td class="">1<br>3<br>7</td>
<td class="">15</td>
<td class="">2<br>6<br>7</td>
<td class="">5<br>6<br>8</td>
<td class="">98</td>
<td class="">4<br>6<br>8</td>
<td class="">2<br>2<br>8</td>
<td class="">26</td>
<td class="">4<br>5<br>7</td>
<td class="">1<br>7<br>8</td>
<td class="">65</td>
<td class="">4<br>5<br>6</td>
<td class="">1<br>3<br>8</td>
<td class="">24</td>
<td class="">6<br>8<br>0</td>
</tr> <tr>
<td>26/12/2022<br />to<br />01/01/2023</td>
<td class="">1<br>5<br>7</td>
<td class="">35</td>
<td class="">1<br>5<br>9</td>
<td class="">3<br>8<br>9</td>
<td class="">08</td>
<td class="">5<br>6<br>7</td>
<td class="">4<br>7<br>8</td>
<td class="">91</td>
<td class="">2<br>2<br>7</td>
<td class="">6<br>8<br>9</td>
<td class="">35</td>
<td class="">1<br>4<br>0</td>
<td class="">3<br>5<br>6</td>
<td class="">45</td>
<td class="">3<br>4<br>8</td>
<td class="">1<br>7<br>9</td>
<td class="">73</td>
<td class="">2<br>5<br>6</td>
<td class="">4<br>8<br>0</td>
<td class="">26</td>
<td class="">3<br>5<br>8</td>
</tr> <tr>
<td>02/01/2023<br />to<br />08/01/2023</td>
<td class="">2<br>6<br>6</td>
<td class="">40</td>
<td class="">3<br>8<br>9</td>
<td class="">1<br>6<br>0</td>
<td class="">73</td>
<td class="">7<br>7<br>9</td>
<td class="">5<br>9<br>0</td>
<td class="">42</td>
<td class="">6<br>7<br>9</td>
<td class="">9<br>9<br>0</td>
<td class="">85</td>
<td class="">1<br>2<br>2</td>
<td class="">3<br>8<br>9</td>
<td class="">01</td>
<td class="">6<br>7<br>8</td>
<td class="">2<br>5<br>8</td>
<td class="">51</td>
<td class="">1<br>0<br>0</td>
<td class="">1<br>3<br>0</td>
<td class="">42</td>
<td class="">2<br>2<br>8</td>
</tr> <tr>
<td>09/01/2023<br />to<br />15/01/2023</td>
<td class="">1<br>9<br>0</td>
<td class="">03</td>
<td class="">3<br>3<br>7</td>
<td class="">2<br>6<br>8</td>
<td class="">67</td>
<td class="">4<br>5<br>8</td>
<td class="">6<br>6<br>9</td>
<td class="">10</td>
<td class="">6<br>7<br>7</td>
<td class="">1<br>2<br>0</td>
<td class="">39</td>
<td class="">1<br>2<br>6</td>
<td class="">1<br>1<br>8</td>
<td class="">07</td>
<td class="">2<br>5<br>0</td>
<td class="">7<br>8<br>0</td>
<td class="">54</td>
<td class="">1<br>4<br>9</td>
<td class="">2<br>7<br>9</td>
<td class="">89</td>
<td class="">2<br>7<br>0</td>
</tr> <tr>
<td>16/01/2023<br />to<br />22/01/2023</td>
<td class="">6<br>7<br>0</td>
<td class="">35</td>
<td class="">1<br>4<br>0</td>
<td class="r">3<br>5<br>8</td>
<td class="r">61</td>
<td class="r">6<br>7<br>8</td>
<td class="">9<br>9<br>0</td>
<td class="">89</td>
<td class="">3<br>8<br>8</td>
<td class="">7<br>8<br>9</td>
<td class="">46</td>
<td class="">7<br>9<br>0</td>
<td class="">3<br>7<br>0</td>
<td class="">01</td>
<td class="">5<br>6<br>0</td>
<td class="">3<br>5<br>0</td>
<td class="">87</td>
<td class="">8<br>9<br>0</td>
<td class="">1<br>4<br>6</td>
<td class="">14</td>
<td class="">1<br>6<br>7</td>
</tr> <tr>
<td>23/01/2023<br />to<br />29/01/2023</td>
<td class="">5<br>7<br>8</td>
<td class="">02</td>
<td class="">6<br>7<br>9</td>
<td class="">3<br>6<br>7</td>
<td class="">65</td>
<td class="">2<br>5<br>8</td>
<td class="">2<br>5<br>0</td>
<td class="">75</td>
<td class="">2<br>3<br>0</td>
<td class="r">*<br>*<br>*</td>
<td class="r">**</td>
<td class="r">*<br>*<br>*</td>
<td class="">7<br>8<br>9</td>
<td class="">43</td>
<td class="">2<br>4<br>7</td>
<td class="">2<br>8<br>9</td>
<td class="">93</td>
<td class="">6<br>7<br>0</td>
<td class="">4<br>5<br>7</td>
<td class="">64</td>
<td class="">2<br>3<br>9</td>
</tr> <tr>
<td>30/01/2023<br />to<br />05/02/2023</td>
<td class="">8<br>8<br>9</td>
<td class="">56</td>
<td class="">1<br>1<br>4</td>
<td class="r">1<br>4<br>9</td>
<td class="r">49</td>
<td class="r">2<br>3<br>4</td>
<td class="">5<br>5<br>6</td>
<td class="">63</td>
<td class="">3<br>4<br>6</td>
<td class="">2<br>9<br>9</td>
<td class="">04</td>
<td class="">3<br>4<br>7</td>
<td class="">2<br>4<br>8</td>
<td class="">42</td>
<td class="">4<br>8<br>0</td>
<td class="">2<br>2<br>4</td>
<td class="">86</td>
<td class="">6<br>0<br>0</td>
<td class="">1<br>3<br>6</td>
<td class="">03</td>
<td class="">1<br>5<br>7</td>
</tr> <tr>
<td>06/02/2023<br />to<br />12/02/2023</td>
<td class="">2<br>9<br>0</td>
<td class="">17</td>
<td class="">4<br>6<br>7</td>
<td class="">3<br>4<br>7</td>
<td class="">43</td>
<td class="">1<br>2<br>0</td>
<td class="">5<br>8<br>9</td>
<td class="">20</td>
<td class="">5<br>6<br>9</td>
<td class="">5<br>6<br>7</td>
<td class="">81</td>
<td class="">4<br>7<br>0</td>
<td class="">7<br>8<br>9</td>
<td class="">40</td>
<td class="">2<br>8<br>0</td>
<td class="">1<br>8<br>9</td>
<td class="">87</td>
<td class="">2<br>7<br>8</td>
<td class="">1<br>8<br>0</td>
<td class="">91</td>
<td class="">2<br>4<br>5</td>
</tr> <tr>
<td>13/02/2023<br />to<br />19/02/2023</td>
<td class="">4<br>7<br>9</td>
<td class="">03</td>
<td class="">1<br>2<br>0</td>
<td class="">3<br>4<br>7</td>
<td class="">45</td>
<td class="">1<br>5<br>9</td>
<td class="">6<br>7<br>0</td>
<td class="">30</td>
<td class="">1<br>4<br>5</td>
<td class="r">1<br>2<br>9</td>
<td class="r">22</td>
<td class="r">1<br>1<br>0</td>
<td class="r">2<br>8<br>9</td>
<td class="r">99</td>
<td class="r">4<br>5<br>0</td>
<td class="">2<br>6<br>0</td>
<td class="">80</td>
<td class="">1<br>3<br>6</td>
<td class="">1<br>3<br>8</td>
<td class="">23</td>
<td class="">5<br>8<br>0</td>
</tr> <tr>
<td>20/02/2023<br />to<br />26/02/2023</td>
<td class="">1<br>6<br>8</td>
<td class="">54</td>
<td class="">7<br>8<br>9</td>
<td class="">1<br>2<br>3</td>
<td class="">64</td>
<td class="">1<br>4<br>9</td>
<td class="r">2<br>2<br>3</td>
<td class="r">77</td>
<td class="r">1<br>1<br>5</td>
<td class="">3<br>4<br>5</td>
<td class="">29</td>
<td class="">1<br>8<br>0</td>
<td class="">4<br>8<br>0</td>
<td class="">24</td>
<td class="">7<br>8<br>9</td>
<td class="">8<br>9<br>9</td>
<td class="">64</td>
<td class="">1<br>6<br>7</td>
<td class="">1<br>3<br>6</td>
<td class="">04</td>
<td class="">5<br>9<br>0</td>
</tr> <tr>
<td>27/02/2023<br />to<br />05/03/2023</td>
<td class="r">3<br>4<br>0</td>
<td class="r">77</td>
<td class="r">5<br>6<br>6</td>
<td class="">1<br>4<br>0</td>
<td class="">59</td>
<td class="">1<br>8<br>0</td>
<td class="">1<br>6<br>7</td>
<td class="">47</td>
<td class="">1<br>6<br>0</td>
<td class="">5<br>8<br>9</td>
<td class="">28</td>
<td class="">2<br>6<br>0</td>
<td class="r">*<br>*<br>*</td>
<td class="r">**</td>
<td class="r">*<br>*<br>*</td>
<td class="">2<br>9<br>0</td>
<td class="">19</td>
<td class="">1<br>2<br>6</td>
<td class="">4<br>4<br>0</td>
<td class="">85</td>
<td class="">1<br>6<br>8</td>
</tr> <tr>
<td>06/03/2023<br />to<br />12/03/2023</td>
<td class="">4<br>5<br>9</td>
<td class="">84</td>
<td class="">4<br>4<br>6</td>
<td class="">6<br>7<br>0</td>
<td class="">31</td>
<td class="">1<br>4<br>6</td>
<td class="r">*<br>*<br>*</td>
<td class="r">**</td>
<td class="r">*<br>*<br>*</td>
<td class="r">*<br>*<br>*</td>
<td class="r">**</td>
<td class="r">*<br>*<br>*</td>
<td class="r">2<br>2<br>8</td>
<td class="r">22</td>
<td class="r">1<br>2<br>9</td>
<td class="">1<br>6<br>8</td>
<td class="">53</td>
<td class="">2<br>4<br>7</td>
<td class="">8<br>9<br>0</td>
<td class="">70</td>
<td class="">1<br>2<br>7</td>
</tr> <tr>
<td>13/03/2023<br />to<br />19/03/2023</td>
<td class="">1<br>2<br>3</td>
<td class="">68</td>
<td class="">2<br>6<br>0</td>
<td class="r">2<br>7<br>0</td>
<td class="r">99</td>
<td class="r">3<br>6<br>0</td>
<td class="">1<br>2<br>0</td>
<td class="">37</td>
<td class="">1<br>6<br>0</td>
<td class="">4<br>5<br>6</td>
<td class="">57</td>
<td class="">8<br>9<br>0</td>
<td class="">5<br>6<br>8</td>
<td class="">93</td>
<td class="">1<br>2<br>0</td>
<td class="">4<br>6<br>0</td>
<td class="">07</td>
<td class="">4<br>6<br>7</td>
<td class="">1<br>5<br>9</td>
<td class="">57</td>
<td class="">2<br>5<br>0</td>
</tr> <tr>
<td>20/03/2023<br />to<br />26/03/2023</td>
<td class="r">7<br>8<br>0</td>
<td class="r">55</td>
<td class="r">1<br>4<br>0</td>
<td class="">4<br>6<br>8</td>
<td class="">89</td>
<td class="">2<br>3<br>4</td>
<td class="">2<br>4<br>0</td>
<td class="">64</td>
<td class="">3<br>4<br>7</td>
<td class="">1<br>2<br>9</td>
<td class="">25</td>
<td class="">1<br>4<br>0</td>
<td class="">1<br>2<br>6</td>
<td class="">98</td>
<td class="">3<br>7<br>8</td>
<td class="">4<br>5<br>0</td>
<td class="">93</td>
<td class="">1<br>3<br>9</td>
<td class="">1<br>6<br>9</td>
<td class="">68</td>
<td class="">5<br>6<br>7</td>
</tr> <tr>
<td>23/07/2023<br />to<br />02/04/2023</td>
<td class="">4<br>5<br>8</td>
<td class="">73</td>
<td class="">2<br>5<br>6</td>
<td class="">1<br>1<br>3</td>
<td class="">59</td>
<td class="">5<br>6<br>8</td>
<td class="r">1<br>2<br>7</td>
<td class="r">05</td>
<td class="r">3<br>5<br>7</td>
<td class="">5<br>6<br>7</td>
<td class="">87</td>
<td class="">2<br>2<br>3</td>
<td class="">1<br>8<br>0</td>
<td class="">93</td>
<td class="">6<br>8<br>9</td>
<td class="">1<br>2<br>3</td>
<td class="">64</td>
<td class="">6<br>8<br>0</td>
<td class="">6<br>6<br>7</td>
<td class="">97</td>
<td class="">3<br>4<br>0</td>
</tr> <tr>
<td>03/04/2023<br />to<br />09/04/2023</td>
<td class="">4<br>7<br>8</td>
<td class="">98</td>
<td class="">9<br>9<br>0</td>
<td class="r">5<br>6<br>9</td>
<td class="r">05</td>
<td class="r">2<br>3<br>0</td>
<td class="">2<br>7<br>8</td>
<td class="">79</td>
<td class="">4<br>6<br>9</td>
<td class="">6<br>7<br>9</td>
<td class="">24</td>
<td class="">7<br>7<br>0</td>
<td class="">3<br>6<br>0</td>
<td class="">91</td>
<td class="">1<br>3<br>7</td>
<td class="">2<br>4<br>0</td>
<td class="">65</td>
<td class="">1<br>1<br>3</td>
<td class="r">1<br>6<br>9</td>
<td class="r">66</td>
<td class="r">2<br>5<br>9</td>
</tr> <tr>
<td>10/04/2023<br />to<br />16/04/2023</td>
<td class="r">5<br>7<br>0</td>
<td class="r">27</td>
<td class="r">1<br>6<br>0</td>
<td class="">1<br>3<br>9</td>
<td class="">31</td>
<td class="">1<br>2<br>8</td>
<td class="">5<br>8<br>9</td>
<td class="">20</td>
<td class="">1<br>3<br>6</td>
<td class="">2<br>8<br>9</td>
<td class="">93</td>
<td class="">2<br>4<br>7</td>
<td class="">2<br>6<br>7</td>
<td class="">51</td>
<td class="">3<br>3<br>5</td>
<td class="">2<br>5<br>7</td>
<td class="">45</td>
<td class="">1<br>5<br>9</td>
<td class="r">2<br>3<br>4</td>
<td class="r">94</td>
<td class="r">1<br>4<br>9</td>
</tr> <tr>
<td>17/04/2023<br />to<br />23/04/2023</td>
<td class="">1<br>3<br>6</td>
<td class="">08</td>
<td class="">2<br>6<br>0</td>
<td class="">5<br>8<br>0</td>
<td class="">37</td>
<td class="">1<br>6<br>0</td>
<td class="">2<br>9<br>0</td>
<td class="">19</td>
<td class="">5<br>6<br>8</td>
<td class="">1<br>6<br>7</td>
<td class="">45</td>
<td class="">6<br>9<br>0</td>
<td class="">7<br>9<br>9</td>
<td class="">54</td>
<td class="">6<br>8<br>0</td>
<td class="">2<br>7<br>9</td>
<td class="">86</td>
<td class="">1<br>6<br>9</td>
<td class="">1<br>0<br>0</td>
<td class="">19</td>
<td class="">4<br>5<br>0</td>
</tr>

<?php 
include '../config.php';
$gh = mysqli_query($con,"SELECT * FROM panel where gameName = 'SAGAR DAY' ORDER BY id ");
include 'panel-chart_amp.php';
?>

</tbody>
</table>
</div>
</div>
		</div>
	<div class="clear">&nbsp;</div>
</div>
<div class="container-fluid footer-text-div">
<p>Welcome to DPBoss Services, your trusted partner in the world of online matka gaming. We take pride in providing accurate and timely Sagar Bazar Day Panel Chart Records to enhance your gaming experience. Our commitment to transparency and reliability sets us apart, ensuring that you have access to the most up-to-date information for making informed decisions.</p>
<br>
<div class="small-heading">Sagar Bazar Day Panel Chart Records: Unveiling the Game's History</div>
<p>At DPBoss, we understand the significance of historical data in the matka world. Our Sagar Bazar Day Panel Chart Records offer a comprehensive overview of past results, helping you analyze patterns, make strategic moves, and improve your chances of winning. With a user-friendly interface, you can easily navigate through the chart records, gaining valuable insights into the game's trends and fluctuations.</p>
<br>
<div class="faq-heading">Frequently Asked Questions (FAQ) for Sagar Bazar Day Panel Chart Records:</div>
<p class="faq-title">Q1: How frequently are the Sagar Bazar Day Panel Chart Records updated?</p>
<p class="faq-ans">We take pride in our commitment to providing real-time and accurate information. The Sagar Bazar Day Panel Chart Records on our platform are updated regularly, ensuring that you have the latest data at your fingertips. Our team works diligently to maintain a seamless and efficient updating process.</p>
<p class="faq-title">Q2: Is there any cost associated with accessing the Sagar Bazar Day Panel Chart Records on DPBoss?</p>
<p class="faq-ans">No, accessing the Sagar Bazar Day Panel Chart Records on DPBoss is completely free of charge. We believe in making essential information accessible to all our users without any financial barriers. Enjoy the convenience of exploring historical data without worrying about subscription fees or hidden costs.</p>
</div><br><br>


<?php include_once('../shortcut_amp.php'); ?> 
</body>
</html>